version: "2"

services:
  tracker:
    container_name: fdfs_tracker
    image: klzsysy/fdfs:5.11
    restart: always
    environment:
      - TRACKER_PORT=22122
    network_mode: "host"
    volumes:
      - ./tracker:/var/local/fdfs/tracker
    command: tracker

  storage:
    container_name: fdfs_storage
    image: klzsysy/fdfs:5.11
    restart: always
    environment:
      # tracker server地址可多个，多个时候变量加数字即可
      # - TRACKER_SERVER1=x.x.x.x:yy
      # - TRACKER_SERVER2=x.x.x.x:yy
      # - TRACKER_SERVER..=....
      # 只有一个tracker server 如下：
      # IP:PORT
      - TRACKER_SERVER=192.195.24.142:22122
      # 当group有多个时增加数量
      - GROUP_COUNT=1
      # 当前group名
      - GROUP_NAME=group1
      - STORAGE_PORT=23000
      # 内置nginx端口
      - HTTP_SERVER_PORT=8080
    network_mode: "host"
    volumes:
      - ./storage:/var/local/fdfs/storage
    command: storage
